import { useEffect, useState } from 'react';
import { ChevronDown, CircleAlert, Filter, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import apiRequest from '../services/api';

const labels = { backlog: 'Aberto', in_progress: 'Em execução', in_review: 'Em análise', done: 'Concluído' };
const emptyForm = { title: '', description: '', projectId: '', assigneeId: '', status: 'backlog', priority: 'medium', dueDate: '' };

export default function TasksPage() {
  const [tasks, setTasks] = useState([]); const [projects, setProjects] = useState([]); const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null);
  const [filters, setFilters] = useState({ projectId: '', status: '', priority: '', search: '' });
  async function loadData() { try { const query = new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))); const [taskResponse, projectResponse] = await Promise.all([apiRequest(`/tasks?${query}`), apiRequest('/projects')]); setTasks(taskResponse.data || []); setProjects(projectResponse.data || []); setUsers(Array.from(new Map((projectResponse.data || []).flatMap((project) => project.members || []).map((item) => [item.id, item])).values())); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadData(); }, [filters]);
  async function handleSubmit(event) { event.preventDefault(); setError(''); try { const payload = { ...form, projectId: Number(form.projectId), assigneeId: form.assigneeId || null, dueDate: form.dueDate || null }; await apiRequest(editingId ? `/tasks/${editingId}` : '/tasks', { method: editingId ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setForm(emptyForm); setEditingId(null); setFormOpen(false); await loadData(); } catch (err) { setError(err.message); } }
  function startEdit(task) { setEditingId(task.id); setForm({ title: task.title, description: task.description || '', projectId: task.project_id, assigneeId: task.assignee_id || '', status: task.status, priority: task.priority, dueDate: task.due_date?.slice(0, 10) || '' }); setFormOpen(true); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function remove(id) { if (!window.confirm('Excluir este registro permanentemente?')) return; try { await apiRequest(`/tasks/${id}`, { method: 'DELETE' }); await loadData(); } catch (err) { setError(err.message); } }
  return <>
    <div className="page-header"><div><span className="eyebrow">Gestão operacional</span><h1 className="page-title">Registros e solicitações</h1><p className="muted">Acompanhe responsáveis, prazos e andamento em uma visão consolidada.</p></div><button className="btn btn-primary" onClick={() => setFormOpen((value) => !value)}><Plus size={16} /> Novo registro <ChevronDown size={14} /></button></div>
    {error && <div className="error-banner"><CircleAlert size={18} />{error}</div>}
    <div className={`form-drawer card ${formOpen ? 'is-open' : ''}`}><form className="section-card" onSubmit={handleSubmit}><div className="form-grid"><label className="field"><span>Título</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label className="field"><span>Operação</span><select value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value })} required><option value="">Selecione</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Responsável</span><select value={form.assigneeId} onChange={(e) => setForm({ ...form, assigneeId: e.target.value })}><option value="">Não atribuído</option>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Status</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{Object.entries(labels).map(([key,value]) => <option key={key} value={key}>{value}</option>)}</select></label><label className="field"><span>Prioridade</span><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Baixa</option><option value="medium">Normal</option><option value="high">Alta</option><option value="urgent">Crítica</option></select></label><label className="field"><span>Prazo</span><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label></div><label className="field" style={{marginTop:16}}><span>Descrição</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-actions"><button className="btn btn-primary">{editingId ? 'Salvar alterações' : 'Criar registro'}</button><button className="btn btn-secondary" type="button" onClick={() => { setFormOpen(false); setEditingId(null); setForm(emptyForm); }}>Cancelar</button></div></form></div>
    <section className="card section-card"><div className="toolbar"><div className="filter-title"><Filter size={16}/><strong>Filtros</strong><span>{tasks.length} registros</span></div><div className="filters"><label className="search-control"><Search size={15}/><input placeholder="Código ou assunto" value={filters.search} onChange={(e) => setFilters({...filters,search:e.target.value})}/></label><select value={filters.projectId} onChange={(e) => setFilters({...filters,projectId:e.target.value})}><option value="">Todas as operações</option>{projects.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={filters.status} onChange={(e)=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{Object.entries(labels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></div></div>
      <div className="table-wrap"><table className="table"><thead><tr><th>Código</th><th>Assunto</th><th>Operação</th><th>Responsável</th><th>Prioridade</th><th>Status</th><th>Prazo</th><th aria-label="Ações" /></tr></thead><tbody>{loading ? [1,2,3].map((n)=><tr key={n}><td colSpan="8"><div className="skeleton" style={{height:24}} /></td></tr>) : tasks.length === 0 ? <tr><td colSpan="8"><div className="empty-state">Nenhum registro encontrado.</div></td></tr> : tasks.map((task)=><tr key={task.id}><td><span className="record-code">REG-{String(task.id).padStart(4,'0')}</span></td><td><strong>{task.title}</strong><div className="muted">{task.description || 'Sem descrição'}</div></td><td>{task.project_name}</td><td>{task.assignee_name || 'Não atribuído'}</td><td><span className={`badge ${task.priority}`}>{task.priority === 'urgent' ? 'Crítica' : task.priority === 'high' ? 'Alta' : task.priority === 'low' ? 'Baixa' : 'Normal'}</span></td><td><span className={`badge ${task.status}`}>{labels[task.status]}</span></td><td>{task.due_date ? new Date(task.due_date).toLocaleDateString('pt-BR') : '—'}</td><td><div className="row-actions"><button onClick={()=>startEdit(task)} data-tooltip="Editar"><Pencil size={15}/></button><button onClick={()=>remove(task.id)} data-tooltip="Excluir"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>
    </section>
  </>;
}
